---
version: "3.8"
services:

  kubeml-api-gateway:
    image: lucmichalski/kubeml-api-gateway:1.1.0
    build: 
      context: ./haproxy
      dockerfile: Dockerfile
    container_name: ${NAMESPACE}-gateway
    ports:
    - 1234:1234
    - 1235:70
    restart: unless-stopped
    networks:
    - internal
    - web  
    depends_on:
    - kubeml-kubernetes-backend
    - kubeml-stripe-backend
    - kubeml-frontend-server

  kubeml-kubernetes-backend:
    image: lucmichalski/kubeml-kubernetes-backend:1.1.0
    build: 
      context: ./kubeml-kubernetes-backend
      dockerfile: Dockerfile
    container_name: ${NAMESPACE}-kubernetes
    ports:
    - 5050:5050
    environment:
      FIREBASE_API_KEY: ${FIREBASE_API_KEY}
      FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
      FIREBASE_DATABASE_URL: ${FIREBASE_DATABASE_URL}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
      FIREBASE_MESSAGING_SENDER_ID: ${FIREBASE_MESSAGING_SENDER_ID}
      FIREBASE_APP_ID: ${FIREBASE_APP_ID}
      FIREBASE_MEASUREMENT_ID: ${FIREBASE_MEASUREMENT_ID}
    networks:
    - internal
    restart: unless-stopped
    hostname: kubeml-kubernetes-backend

  kubeml-stripe-backend:
    image: lucmichalski/kubeml-stripe-backend:1.1.0
    build: 
      context: ./kubeml-stripe-backend
      dockerfile: Dockerfile
    container_name: ${NAMESPACE}-stripe
    environment:
      FIREBASE_API_KEY: ${FIREBASE_API_KEY}
      FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
      FIREBASE_DATABASE_URL: ${FIREBASE_DATABASE_URL}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
      FIREBASE_MESSAGING_SENDER_ID: ${FIREBASE_MESSAGING_SENDER_ID}
      FIREBASE_APP_ID: ${FIREBASE_APP_ID}
      FIREBASE_MEASUREMENT_ID: ${FIREBASE_MEASUREMENT_ID}
    networks:
    - internal
    ports:
    - 8080:8080
    restart: unless-stopped
    hostname: kubeml-stripe-backend

  kubeml-frontend-server:
    image: lucmichalski/kubeml-frontend-server:1.1.0
    build: 
      context: ./kubeml-frontend-server
      dockerfile: Dockerfile
    container_name: ${NAMESPACE}-frontend
    ports:
    - 6060:6060
    networks:
    - internal
    restart: unless-stopped
    hostname: kubeml-frontend-server

networks:
  internal:
    driver: bridge
  web:
    external: true