---
version: "3.8"
services:

  # kubeml-dev:
  #   image: lucmichalski/kube-ml-dev:alpine-latest
  #   container_name: ${NAMESPACE}-core
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #   - .:/opt/seoz-naxly
  #   environment:
  #   - STRIPE_SECRET_KEY=""
  #   - NODE_ENV="production"
  #   ports:
  #   - 5000:5000

  kubeml-api-gateway:
    build: ./haproxy
    image: kubemlregistry/kubeml-api-gateway:1.1.0
    ports:
    - 1234:80
    restart: unless-stopped

  kubeml-kubernetes-backend:
    build: ./kubeml-kubernetes-backend
    image: kubemlregistry/kubeml-kubernetes-backend:1.1.0
    ports:
    - 5050:5050
    environment:
      FIREBASE_API_KEY: ""
      FIREBASE_AUTH_DOMAIN: ""
      FIREBASE_DATABASE_URL: ""
      FIREBASE_PROJECT_ID: ""
      FIREBASE_STORAGE_BUCKET: ""
      FIREBASE_MESSAGING_SENDER_ID: ""
      FIREBASE_APP_ID: ""
      FIREBASE_MEASUREMENT_ID: ""
    restart: unless-stopped
    hostname: kubeml-kubernetes-backend

  kubeml-stripe-backend:
    build: ./kubeml-stripe-backend
    image: kubemlregistry/kubeml-stripe-backend:1.1.0
    ports:
    - 8080:8080
    restart: unless-stopped
    hostname: kubeml-stripe-backend

  kubeml-frontend-server:
    build: ./kubeml-frontend-server
    image: kubemlregistry/kubeml-frontend-server:1.1.0
    ports:
    - 6060:6060
    restart: unless-stopped
    hostname: kubeml-frontend-server
    #environment:
    #- PORT=6060