version: "3"

services:
  kubeml-api-gateway:
    build: ./haproxy
    image: kubemlregistry/kubeml-api-gateway:1.2.0
    ports:
      - 1234:80
    restart: always

  kubeml-kubernetes-backend:
    build: ./kubeml-kubernetes-backend
    image: kubemlregistry/kubeml-kubernetes-backend:1.3.0
    volumes:
      - ~/.kube/config:/home/node/.kube/config
    environment:
      FIREBASE_API_KEY: AIzaSyBD87B8drIK2NNLr-5e4PMYMEDQmKDP8pw
      FIREBASE_AUTH_DOMAIN: kube-ml.firebaseapp.com
      FIREBASE_DATABASE_URL: https://kube-ml.firebaseio.com
      FIREBASE_PROJECT_ID: kube-ml
      FIREBASE_STORAGE_BUCKET: kube-ml.appspot.com
      FIREBASE_MESSAGING_SENDER_ID: 550937035835
      FIREBASE_APP_ID: 1:550937035835:web:7f023a1d494c948592481e
      FIREBASE_MEASUREMENT_ID: G-MVRXP6G97S
    ports:
      - 5050:5050
    restart: always
    hostname: kubeml-kubernetes-backend

  kubeml-stripe-backend:
    build: ./kubeml-stripe-backend
    image: kubemlregistry/kubeml-stripe-backend:1.3.0
    environment:
      FIREBASE_API_KEY: AIzaSyBD87B8drIK2NNLr-5e4PMYMEDQmKDP8pw
      FIREBASE_AUTH_DOMAIN: kube-ml.firebaseapp.com
      FIREBASE_DATABASE_URL: https://kube-ml.firebaseio.com
      FIREBASE_PROJECT_ID: kube-ml
      FIREBASE_STORAGE_BUCKET: kube-ml.appspot.com
      FIREBASE_MESSAGING_SENDER_ID: 550937035835
      FIREBASE_APP_ID: 1:550937035835:web:7f023a1d494c948592481e
      FIREBASE_MEASUREMENT_ID: G-MVRXP6G97S
    ports:
      - 8080:8080
    restart: always
    hostname: kubeml-stripe-backend

  kubeml-frontend-server:
    build: ./kubeml-frontend-server
    image: kubemlregistry/kubeml-frontend-server:1.9.0
    ports:
      - 6060:6060
    restart: always
    hostname: kubeml-frontend-server
