{{- if .Values.ingress2.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jupyterhub
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
  {{- if .Values.ingress2.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingress2.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress2.hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
          - path: {{ $.Values.hub.baseUrl }}{{ $.Values.ingress2.pathSuffix }}
            backend:
              serviceName: proxy-public
              servicePort: 80
    {{- end }}
  {{- if .Values.ingress2.tls }}
  tls:
    {{- .Values.ingress2.tls | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
{{- end }}
