const PRICE_DATA = {
  ec2: [
    {
      _id: 0,
      type: "t3.large",
      vCPU: 2,
      RAM: 8,
      Processor_Name: "Intel Skylake P-8175",
      Clock_Speed: 2.5,
      SageMaker: 0.1165,
      On_Demand: 0.0832,
      Long_Term: 0.052,
    },
    {
      _id: 1,
      type: "m5.xlarge",
      vCPU: 4,
      RAM: 16,
      Processor_Name: "Intel Xeon Platinum 8175",
      Clock_Speed: 3.1,
      SageMaker: 0.269,
      On_Demand: 0.192,
      Long_Term: 0.121,
    },
    {
      _id: 2,
      type: "m5.2xlarge",
      vCPU: 8,
      RAM: 32,
      Processor_Name: "Intel Xeon Platinum 8175",
      Clock_Speed: 3.1,
      SageMaker: 0.538,
      On_Demand: 0.384,
      Long_Term: 0.242,
    },
    {
      _id: 3,
      type: "m5.4xlarge",
      vCPU: 16,
      RAM: 64,
      Processor_Name: "Intel Xeon Platinum 8175",
      Clock_Speed: 3.1,
      SageMaker: 1.075,
      On_Demand: 0.768,
      Long_Term: 0.484,
    },
    {
      _id: 4,
      type: "m4.10xlarge",
      vCPU: 40,
      RAM: 160,
      Processor_Name: "Intel Xeon E5-2676v3",
      Clock_Speed: 2.4,
      SageMaker: 2.8,
      On_Demand: 2.0,
      Long_Term: 1.239,
    },
    {
      _id: 5,
      type: "m5.12xlarge",
      vCPU: 48,
      RAM: 196,
      Processor_Name: "Intel Xeon Platinum 8175",
      Clock_Speed: 3.1,
      SageMaker: 3.226,
      On_Demand: 2.304,
      Long_Term: 1.452,
    },
    {
      _id: 6,
      type: "m4.16xlarge",
      vCPU: 64,
      RAM: 256,
      Processor_Name: "Intel Xeon E5-2676v4",
      Clock_Speed: 2.3,
      SageMaker: 4.48,
      On_Demand: 3.2,
      Long_Term: 1.982,
    },
    {
      _id: 7,
      type: "m5.24xlarge",
      vCPU: 96,
      RAM: 384,
      Processor_Name: "Intel Xeon Platinum 8175",
      Clock_Speed: 3.1,
      SageMaker: 6.451,
      On_Demand: 4.608,
      Long_Term: 2.903,
    },
  ],
};

export default PRICE_DATA;

// SageMaker on average 40% more expensive than base on-demand. K
// Which means KubeML will save customers 29% on average for on-demand

// LongTerm Nodes are on average 65% cheaper or SageMaker is 224% more expensive
